// <auto-generated />
using System;
using BBS.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BBS.Migrations
{
    [DbContext(typeof(DBcontext))]
    partial class DBcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BBS.Models.Roles.Role", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreateDate")
                        .HasColumnName("CreateTime")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LoginDate")
                        .HasColumnName("LoginTime")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .HasColumnName("role_name")
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Password")
                        .HasColumnName("pass")
                        .HasColumnType("int");

                    b.Property<string>("RegName")
                        .HasColumnName("reg_name")
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ID");

                    b.ToTable("role");
                });

            modelBuilder.Entity("BBS.Models.Roles.RoleInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreateDate")
                        .HasColumnName("CreateTime")
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Level")
                        .HasColumnName("lvl")
                        .HasColumnType("int");

                    b.Property<string>("LoginDate")
                        .HasColumnName("LoginTime")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 64)))
                        .HasColumnName("phone")
                        .HasColumnType("nvarchar(13)");

                    b.Property<int>("Sex")
                        .HasColumnName("sex")
                        .HasColumnType("int");

                    b.Property<int?>("rid");

                    b.HasKey("ID");

                    b.HasIndex("rid")
                        .IsUnique()
                        .HasFilter("[rid] IS NOT NULL");

                    b.ToTable("role_info");
                });

            modelBuilder.Entity("BBS.Models.Roles.RoleInfo", b =>
                {
                    b.HasOne("BBS.Models.Roles.Role", "Rid")
                        .WithOne("roleinfo")
                        .HasForeignKey("BBS.Models.Roles.RoleInfo", "rid");
                });
#pragma warning restore 612, 618
        }
    }
}
